### ISSUE TITLE
Create Project Roadmap

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher#39]
Create a comprehensive roadmap for the Legesher project for 2019.

We will be utilizing [ZenHub](https://app.zenhub.com/workspaces/legesher-5cfc8882a194951888ed8a5a/board?repos=146684156,180825785,166074895,156307499,143786072) for maintaining and organizing the roadmap for the entire Legesher project. 

- [x] Research what project roadmap tool to use
- [x] Set up the project roadmap in ZenHub for the entire project
- [x] Create Sprint 06/12/19 that will take place from 06/12/2019 - 06/26/2019
- [x] Add new milestone for work that was completed before project management
- [x] Add all closed issues to the previous sprint
- [x] Add `legesher`'s repository to the project roadmap workspace
- [x] Add `legesher-docs`'s repository to the project roadmap workspace
- [x] Add `legesher-dot-io`'s repository to the project roadmap workspace
- [x] Add `tree-sitter-legesher-python`'s repository to the project roadmap workspace
- [x] Add `language-legesher-python`'s repository to the project roadmap workspace
- [x] Clean up old project roadmaps in the individual project repositories
- [x] Add user stories / github issues that will be in the sprint
- [x] Clean user stories / github issues that will be in the sprint
- [x] Add issues to the **Development Backlog** for the next sprint
- [x] Create Epics for the Legesher project
- [x] Organize github issues in the Epics
- [x] Add new labels after update

**Comment by madiedgar** [comment]
I'm going to reclose this issue. When the time comes to update the roadmap, we'll reference this one in a new issue.
